[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = ".next/functions"

# Add this to disable blobs temporarily
[build.environment]
  NETLIFY_BLOBS_DISABLED = "true"

# Optional: Add redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200